# Generated by Django 3.1 on 2020-08-22 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categories',
            old_name='parent_id',
            new_name='parent',
        ),
        migrations.RenameField(
            model_name='posts',
            old_name='category_id',
            new_name='category',
        ),
    ]
