# Generated by Django 3.1 on 2020-10-18 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_auto_20201018_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ManyToManyField(related_name='_post_category_+', to='post.Category'),
        ),
    ]
