# Generated by Django 3.1 on 2020-10-19 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_auto_20201018_2003'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='string',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(default=''),
        ),
    ]
